### PR TITLE
ADO Trigger Pipeline

### PR DESCRIPTION
**Pull request by rajvi**
- Trigger pipeline yaml
- Invoke ADO unit tests pipeline, wait for build, get report status
- Use github_pr as source branch to avoid conflicts with master branch for README status badge
- Tested flow end to end (GH and ADO pipelines) - succeeds on success case and fails and blocks PR if unit tests fail

### CODE REVIEW

**Comment by rafsalas19** [comment]
Can you squash all commits into 1 or 2 commit messages relevant to the high level changes.

**Comment by rajvi** [comment]
> Can you squash all commits into 1 or 2 commit messages relevant to the high level changes.

done!

**Review by yakovdyadkin — APPROVED** [review]

**Pull request merged**
